### ISSUE TITLE
CSS architecture improvements

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#1046]
# What

Pulsar has grown organically over the past few years and we suffer from a few long-term issues which affect most large projects.

* high specificity
* code duplication due to improper use of `@import` and `@extends`
* no prior focus on CSS performance monitoring

[Sass modules](https://css-tricks.com/introducing-sass-modules/) have recently been released which would dramatically change how we approach styling Pulsar components, as such it would be a good time for a widespread review and refactor of Pulsar components.

# Why

* [Jadu Directive](https://www.jadu.net/info/20003/how_we_work/6/everything_possible_-_jadus_core_values) 3 - Deliver high quality software
* Improve front-end performance of Jadu products

# Done when

## Must
- [ ] Audit all current components/patterns, decide to keep, replace or retire
- [ ] Document open standard for authoring components/patterns
- [ ] Implement authoring standard in linter, increase linter coverage
- [ ] Identify all stylesheets to be refactored
- [ ] Generate baseline specificity graph
- [ ] Decide on key metrics for CSS performance (first meaningful paint in each product, for example)
- [ ] Reorganise Sass filesystem

## Should
- [ ] Investigate automation of specificity monitoring
- [ ] Investigate automation of performance monitoring

**Comment by jamesjacobs** [comment]
Also need to investigate the use of `@extend` and `@import`. Some sass partials are imported into other partials resulting in a large amount of duplicated CSS. For example, `toolbar.scss` imports `labels.scss`, which results in any class added to `labels.scss` being duplicated in the css. 

Look at @use rather than @import.

Partials to review (not a complete list):
- `toolbar.scss`
- `labels.scss`
- `buttons.scss`

Check and review any instances of `@import`.
