### ISSUE TITLE
Ensure the Pulsar User interface framework is implemented as an effective library of reusable UI components for Jadu Software

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#1048]
# What

Pulsar is a tool for Jadu engineers to build effective user interfaces. It should be a stable, maintained, supported and funded product with comprehensive documentation.

* We will actively work to reduce friction for Jadu products updating Pulsar versions
* We will reduce the % of non-Pulsar UIs within Jadu products
* We will continually improve our documentation and processes

# Why

* Directive #3 - Deliver high quality software
* Directive #4 - Design with standards, semantics and end users in mind
* Group Objective #5 - Easily installed software

# User needs

_As a member of the Jadu team..._

**1. I know what Pulsar is**
- [x] 1.1 New starters are briefed about Pulsar as part of their bootcamp introduction

**2. Pulsar is available for me to use**
- [x] 2.1 Pulsar is published as an open-source repository on GitHub
- [x] 2.2 Pulsar is available as a dependency for all Jadu software products

**3. I can easily update the version of Pulsar we use**
- [x] 3.1 I am notified when new versions are released
- [x] 3.2 I can find out what changes are in a particular release
- [ ] 3.3 I can be confident that updating to a newer version of Pulsar will not break the build
- [ ] 3.4 I can be confident that updating to a minor or patch version will not break existing UIs
- [x] 3.5 Breaking changes are accompanied by suggested remediation steps
- [x] 3.6 Pulsar releases follow SemVer major.minor.patch protocol

**4. I can find the styles, components and patterns I need to implement a user interface**
- [x] 4.1 There is a single source of documentation that is publicly available
- [ ] 4.2 I can find a list of components which are available for me to use in a given Jadu product
- [x] 4.3 I can find code examples for Twig, Symfony and HTML where applicable
- [x] 4.4 I can find information about any additional options a component may support
- [ ] 4.5 I can find a list of planned components, or those in-progress

**5. I can be confident Pulsar components are accessible**
- [ ] 5.1 There is an open standard for testing the accessibility of Pulsar components
- [x] 5.2 Components are individually tested against WCAG 2.1 AA
- [ ] 5.3 Documentation for a component contains an accessibility section which details current a11y status, known issues and anything particularly important for a developer to know

**6. I can request changes, or suggest a new feature**
- [ ] 6.1 I can easily find out how to raise a ticket to request changes or suggest a new feature
- [ ] 6.2 I am notified when my suggestion has been accepted or rejected (with reasons why)

**7. I can easily contribute back to the Design System**
- [ ] 7.1 There is an open standard for developing custom components and patterns
- [ ] 7.2 There is documentation on how to include a custom component within Jadu products

**8.  I can get help and technical support when I need it**
- [x] 8.1 Pulsar is supported by a permanent team
- [x] 8.2 There is a public #pulsar channel on the Jadu team Slack account that I can join
- [x] 8.3 There is a documented process for raising an issue for the team to respond to

**9. I can override, or use temporary fixes for issues in Jadu products**
- [x] 9.1 I have access to 'scratch' files where I can place styles/javascript temporarily, to fix issues locally before an official Pulsar release is available
- [x] 9.2 I have a way of communicating my changes to the Pulsar team
- [x] 9.3 There is a process where scratched changes are reviewed and incorporated into Pulsar where appropriate
