### ISSUE TITLE
Review all scratch rules used in products

### ISSUE THREAD

**Issue by Stanton** [jadu/pulsar#1053]
# What

Manually review every single CSS declaration in each product's scratch file and actively work to resolve the need for each rule.

# Why

* Directive #3 - _Deliver high quality software_
* Team Objective #1 - _Working closely with all Heads of & Product managers, ensure the Pulsar User interface framework is implemented as an effective library of reusable UI components for Jadu Software_

Having high-specificity rules within products which directly target and override Pulsar increases the unpredictability of Pulsar updates and the risk of unintended visual regressions between releases.

# Done when

## Must

- [x] A high-level task created for each Jadu product and assigned to the appropriate Pulsar team member
- [x] Each product owner made aware of this task
- [x] XFP - All rules in a product scratch file manually reviewed, documented and ticketed
- [x] CMS - All rules in a product scratch file manually reviewed, documented and ticketed
- [ ] CXM - All rules in a product scratch file manually reviewed, documented and ticketed

## Suggested method

For a single CSS declaration within the scratch file, verify that:

* The rule is still required? if not, remove it.
* Does the reason for the rule need to be resolved by changes to Pulsar? If so, ticket it in GitHub, tag with the `scratch rule in use` label, and the affected product label.
* Does the reason for the rule need to be resolved by changes to the Product specific CSS? If so, ticket it in Jira, and update the scratch documentation with that number, then work with the product team to prioritise and resolve it.

Scratch rules should generally follow this format, for more detailed information see the [Pulsar Developer Guide](https://pulsar.docs.jadu.net/guides/developer-guide).

```
/**
 * 04/07/2019 - Paul Stanton
 *
 * Description:
 * Fixes checkbox styling based on updated Pulsar styles which aren’t properly applying the new styles due to
 * high specificity.
 *
 * Affected UIs:
 * https://example.com/path/to/affected-ui
 * https://example.com/path/to/affected-ui
 *
 * Ticket:
 * https://path/to/related/ticket/XFP-1111
 */
.form__control.checkbox.checkbox,
.form__control.radio.radio {
    height: 20px;
    overflow: visible; // stop border from disappearing under left edge of container
    position: relative; // stop radios being misaligned when used in choice groups
    width: 20px;
}
```
